extends: standard

env:
  node: true
  es6: true
  mocha: true

parserOptions:
  ecmaVersion: 2018

rules:
  curly: 0
  eqeqeq: 2
  space-before-function-paren: 0
  arrow-parens: [2, as-needed]
  semi: [2, always]
  no-extra-semi: 2
  dot-location: [2, property]
  prefer-arrow-callback: 2
  prefer-const: 2
  arrow-spacing: [2, {before: true, after: true}]
  no-console: 2
